name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        node-version: '20'  

    - name: Cache Maven packages
      uses: actions/cache@v3  # Use the latest version
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven

    - name: Compile and package the code
      run: ./mvnw package -DskipTests

    - name: Run tests
      run: ./mvnw test

    - name: Package the project as a Docker image
      run: |
        docker build -t spring-petclinic:latest .

    - name: Log in to JFrog Artifactory
      env:
        JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
        JFROG_API_KEY: ${{ secrets.JFROG_API_KEY }}
      run: |
        echo "Logging in to JFrog Artifactory"
        echo $JFROG_API_KEY | docker login https://hiroyukimorimoto.jfrog.io -u $JFROG_USERNAME --password-stdin

    - name: Publish the Docker image to JFrog Artifactory
      run: |
        docker tag spring-petclinic:latest hiroyukimorimoto.jfrog.io/test-docker/spring-petclinic:latest
        docker push push hiroyukimorimoto.jfrog.io/test-docker/spring-petclinic:latest
