name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Compile the code
      run: ./mvnw compile

    - name: Run tests
      run: ./mvnw test

    - name: Package the project as a Docker image
      run: |
        docker build -t spring-petclinic:latest .

    - name: Log in to JFrog Artifactory
      env:
        JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
        JFROG_API_KEY: ${{ secrets.JFROG_API_KEY }}
      run: |
        echo "Logging in to JFrog Artifactory"
        echo $JFROG_API_KEY | docker login hiroyukimorimoto.jfrog.io -u $JFROG_USERNAME --password-stdin

    - name: Publish the Docker image to JFrog Artifactory
      run: |
        docker tag spring-petclinic:latest hiroyukimorimoto.jfrog.io/docker-repo/spring-petclinic:latest
        docker push hiroyukimorimoto.jfrog.io/docker-repo/spring-petclinic:latest

